name: TypePad AntiSpam
id: typepadantispam
key: typepadantispam
author_name: Six Apart Ltd.
author_link: http://www.sixapart.com/
version: 1.0.2
plugin_class: "TypePadAntiSpam::Plugin"

options:
    weight:
      label: 'Junk Score Weight'
      type: select
      scope: blog
      values: '"1 - Least weight":"1",2,3,4,5,6,7,8,9,"10 - Most weight":"10"'
      hint: >
          Comments and TrackBacks receive a junk score between -10 (definitely spam) and +10 (definitely not spam). This setting allows you to control the weight of the TypePad AntiSpam rating relative to other filters you may have installed to help you filter comments and TrackBacks.
    api_key:
      label: 'API Key'
      default: ''
      order: 1
      scope: system
      type: text
      hint: >
         To enable this plugin, you'll need a free TypePad AntiSpam API key. You can <strong>get your free API key at <a href="http://antispam.typepad.com/" target="_blank">antispam.typepad.com</a></strong>. Once you have your key, return to this page and enter it in the field below.'
    service_host:
      label: 'Service Host'
      default: api.antispam.typepad.com
      order: 2
      scope: system
      type: text
      hint: >
          The default service host for TypePad AntiSpam is api.antispam.typepad.com. You should only change this if you are using a different service that is compatible with the TypePad AntiSpam API.

callbacks:
    handle_spam: $TypePadAntiSpam::TypePadAntiSpam::Callbacks::handle_junk
    handle_ham: $TypePadAntiSpam::TypePadAntiSpam::Callbacks::handle_not_junk
    MT::Comment::pre_save: $TypePadAntiSpam::TypePadAntiSpam::Callbacks::pre_save_obj
    MT::TBPing::pre_save: $TypePadAntiSpam::TypePadAntiSpam::Callbacks::pre_save_obj

junk_filters:
    TypePadAntiSpam:
        label: TypePad AntiSpam
        code: $TypePadAntiSpam::TypePadAntiSpam::Plugin::typepadantispam_score

tags:
    function:
        TypePadAntiSpamCounter: $TypePadAntiSpam::TypePadAntiSpam::_hdlr_tpas_counter

widgets:
    typepadantispam:
        label: TypePad AntiSpam
        template: stats_widget.tmpl
        handler: $TypePadAntiSpam::TypePadAntiSpam::Plugin::stats_widget
        set: sidebar
        singular: 1
        order: 2.1
        condition: >
            sub {
                my $plugin = MT->component('TypePadAntiSpam');
                return $plugin->api_key ? 1 : 0;
            }

